import { Activity, ArrowLeftRight, BrainCircuit, Database, GitBranch, Layers3, Server, ShieldAlert, SlidersHorizontal, X } from 'lucide-react'

export default function Sidebar({ currentPath, navigate, counts, mobileOpen, closeMobile }) {
  const groups = [
    { label: 'Monitor', items: [{ path: '/', label: 'Executive overview', icon: Activity }, { path: '/alerts', label: 'Threat alerts', icon: ShieldAlert, badge: counts?.alerts?.total }, { path: '/nodes', label: 'Node profiles', icon: Server, badge: counts?.network?.total_nodes }, { path: '/transactions', label: 'Transaction traffic', icon: ArrowLeftRight, badge: counts?.network?.total_transactions }] },
    { label: 'Investigate', items: [{ path: '/topology', label: 'Network topology', icon: GitBranch }, { path: '/clusters', label: 'Cluster analysis', icon: Layers3 }] },
    { label: 'Govern', items: [{ path: '/models', label: 'ML model registry', icon: BrainCircuit }, { path: '/operations', label: 'Pipeline operations', icon: SlidersHorizontal }] },
  ]

  return <aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><div className="sidebar-header"><div className="brand-mark">₿</div><div className="logo-text"><h1>BlockInsight</h1><p>Network intelligence</p></div><button className="mobile-close icon-button" onClick={closeMobile}><X size={18} /></button></div><div className="sidebar-context"><span className="context-kicker">Analysis workspace</span><strong>Bitcoin P2P telemetry</strong><span className="context-batch">{counts ? `Batch #${counts.batch_id}` : 'Batch unavailable'}</span></div><nav className="nav-links">{groups.map(group => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(item => { const Icon = item.icon; const active = currentPath === item.path; return <button className={`nav-item ${active ? 'active' : ''}`} key={item.path} onClick={() => navigate(item.path)}><Icon size={17} /><span>{item.label}</span>{item.badge !== undefined && <b>{item.badge}</b>}</button> })}</div>)}</nav><div className="sidebar-footer"><div className="footer-line"><Database size={14} /><span>PostgreSQL analytics</span></div><div className="footer-note">Presentation layer · live API state shown above</div></div></aside>
}
